Use struct as context key
garrettladley/fiberpaginate pull request #11
Opened 2024-12-02 15:32 UTC by mutantkeyboard

Based on https://github.com/garrettladley/fiberpaginate/issues/10

2024-12-03 01:28 UTC, garrettladley requested changes
thanks for tackling this! 1 quick thing

2024-12-03 01:28 UTC, garrettladley commented on paginate.go
sorry, i realize the issue was quite vague. let's use an empty struct instead of one with a hardcoded name. [explanation here](https://github.com/garrettladley/go/blob/main/examples/ctx/ctx.go)

2024-12-03 06:25 UTC, mutantkeyboard commented on paginate.go
Sure thing

2024-12-09 07:44 UTC, closed without merging

2024-12-09 07:44 UTC, mutantkeyboard commented
I've synced and pushed all changes via enchancement branch, hence I'll close this PR