Added offset and sorting
garrettladley/fiberpaginate pull request #12
Opened 2024-12-02 16:50 UTC by mutantkeyboard

- Offset
- Sorting (by various conditions)
- More tests

2024-12-03 01:36 UTC, garrettladley requested changes

2024-12-03 01:36 UTC, garrettladley commented on util.go
> +func isAllowedSort(sort string, allowedSorts []string) bool {
is this redundant if the stdlib has [`slices.Contains`](https://pkg.go.dev/slices#Contains)

2024-12-03 01:36 UTC, garrettladley commented on util.go
> +	var sortFields []SortField
since the len of `sortFields` is directly proportional to `len(fields)`, can we allocate a slice of `len(fields)` here?

2024-12-03 01:36 UTC, garrettladley commented on util.go
nit: i don't _love_ `util.go` as a file name, `strings.go` seems more fitting based on the contents

2024-12-03 01:36 UTC, garrettladley commented on util.go
> +func parseSortQuery(query string, allowedSorts []string, defaultSort string) []SortField {
could we add some tests for this?

2025-05-28 14:06 UTC, mutantkeyboard commented
@garrettladley - do I close a PR or just leave it open?

2026-03-10 12:53 UTC, closed without merging